In [ ]:
import pandas as pd
import re
from nltk.corpus import stopwords
from gensim.models import Word2Vec
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from sklearn.ensemble import RandomForestClassifier
from transformers import pipeline,Sentencr
from tqdm import tqdm
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
import warnings 
warnings.filterwarnings("ignore")

d:\Anaconda\envs\gensim-env\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.

In [5]:
import numpy as np

In [6]:
from sentence_transformers import SentenceTransformer

ModuleNotFoundError: No module named 'sentence_transformers'

In [ ]:
df = pd.read_csv("D:\Machine Learning\Datasets\netflix\titles.csv")
df

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
0,ts300399,Five Came Back: The Reference Films,SHOW,This collection includes 12 World War II-era p...,1945,TV-MA,51,['documentation'],['US'],1.0,NaN,NaN,NaN,0.600,NaN
1,tm84618,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,114,"['drama', 'crime']",['US'],NaN,tt0075314,8.2,808582.0,40.965,8.179
2,tm154986,Deliverance,MOVIE,Intent on seeing the Cahulawassee River before...,1972,R,109,"['drama', 'action', 'thriller', 'european']",['US'],NaN,tt0068473,7.7,107673.0,10.010,7.300
3,tm127384,Monty Python and the Holy Grail,MOVIE,"King Arthur, accompanied by his squire, recrui...",1975,PG,91,"['fantasy', 'action', 'comedy']",['GB'],NaN,tt0071853,8.2,534486.0,15.461,7.811
4,tm120801,The Dirty Dozen,MOVIE,12 American military prisoners in World War II...,1967,NaN,150,"['war', 'action']","['GB', 'US']",NaN,tt0061578,7.7,72662.0,20.398,7.600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5845,tm1014599,Fine Wine,MOVIE,A beautiful love story that can happen between...,2021,NaN,100,"['romance', 'drama']",['NG'],NaN,tt13857480,6.8,45.0,1.466,NaN
5846,tm898842,C/O Kaadhal,MOVIE,A heart warming film that explores the concept...,2021,NaN,134,['drama'],[],NaN,tt11803618,7.7,348.0,NaN,NaN
5847,tm1059008,Lokillo,MOVIE,A controversial TV host and comedian who has b...,2021,NaN,90,['comedy'],['CO'],NaN,tt14585902,3.8,68.0,26.005,6.300
5848,tm1035612,Dad Stop Embarrassing Me - The Afterparty,MOVIE,"Jamie Foxx, David Alan Grier and more from the...",2021,PG-13,37,[],['US'],NaN,NaN,NaN,NaN,1.296,10.000
5849,ts271048,Mighty Little Bheem: Kite Festival,SHOW,"With winter behind them, Bheem and his townspe...",2021,NaN,7,"['family', 'animation', 'comedy']",[],1.0,tt13711094,7.8,18.0,2.289,10.000

In [ ]:
crit = ( df['production_countries'].str.contains('IN')) & (df['type']=='MOVIE') & (df['release_year'] >= 1980)
df_ind_mov = df[crit]
df_ind_mov.head()

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
19,tm94651,Dostana,MOVIE,Two close friends decide to enter law enforcem...,1980,NaN,161,"['drama', 'comedy', 'crime', 'romance', 'action']",['IN'],NaN,tt0080653,2.1,25.0,3.980,4.9
56,tm721687,Vaashi,MOVIE,"Ebin Mathew, a budding lawyer ambitiously join...",1983,NaN,123,"['drama', 'thriller']",['IN'],NaN,tt13913068,6.7,388.0,3.790,NaN
65,tm52815,Disco Dancer,MOVIE,"Anil, a street singer, is humiliated and drive...",1982,NaN,106,"['drama', 'romance']",['IN'],NaN,tt0208903,6.4,1476.0,7.879,5.3
66,tm159912,Agneepath,MOVIE,"The movie depicts the life of a young boy, Vij...",1990,NaN,174,"['drama', 'action', 'crime']",['IN'],NaN,tt0098999,7.6,8947.0,4.062,6.5
71,tm157603,Dil,MOVIE,Raja lives a poor lifestyle along with his dad...,1990,NaN,172,"['drama', 'comedy', 'romance']",['IN'],NaN,tt0099429,6.6,5316.0,3.992,6.5

In [ ]:
df_ind_mov.count()

id                      570
title                   570
type                    570
description             570
release_year            570
age_certification       199
runtime                 570
genres                  570
production_countries    570
seasons                   0
imdb_id                 550
imdb_score              545
imdb_votes              545
tmdb_popularity         560
tmdb_score              545
dtype: int64

In [ ]:
df_ind_mov.loc[:, 'info'] = "Title: " + df_ind_mov['title'].copy() + " Description: " + df_ind_mov['description'].copy()
df_ind_mov.head()

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score,info
19,tm94651,Dostana,MOVIE,Two close friends decide to enter law enforcem...,1980,NaN,161,"['drama', 'comedy', 'crime', 'romance', 'action']",['IN'],NaN,tt0080653,2.1,25.0,3.980,4.9,Title: Dostana Description: Two close friends ...
56,tm721687,Vaashi,MOVIE,"Ebin Mathew, a budding lawyer ambitiously join...",1983,NaN,123,"['drama', 'thriller']",['IN'],NaN,tt13913068,6.7,388.0,3.790,NaN,"Title: Vaashi Description: Ebin Mathew, a budd..."
65,tm52815,Disco Dancer,MOVIE,"Anil, a street singer, is humiliated and drive...",1982,NaN,106,"['drama', 'romance']",['IN'],NaN,tt0208903,6.4,1476.0,7.879,5.3,"Title: Disco Dancer Description: Anil, a stree..."
66,tm159912,Agneepath,MOVIE,"The movie depicts the life of a young boy, Vij...",1990,NaN,174,"['drama', 'action', 'crime']",['IN'],NaN,tt0098999,7.6,8947.0,4.062,6.5,Title: Agneepath Description: The movie depict...
71,tm157603,Dil,MOVIE,Raja lives a poor lifestyle along with his dad...,1990,NaN,172,"['drama', 'comedy', 'romance']",['IN'],NaN,tt0099429,6.6,5316.0,3.992,6.5,Title: Dil Description: Raja lives a poor life...

In [ ]:
print(df_ind_mov['info'].head())

19    Title: Dostana Description: Two close friends ...
56    Title: Vaashi Description: Ebin Mathew, a budd...
65    Title: Disco Dancer Description: Anil, a stree...
66    Title: Agneepath Description: The movie depict...
71    Title: Dil Description: Raja lives a poor life...
Name: info, dtype: object

In [ ]:
model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2", token="hf_LJfVazBKDAmmoLJubhsJkMRSyaHaulEFcln")

In [ ]:
all_desc = list( df_ind_mov['info'])
out_embs = []
for r in tqdm(all_desc):
    embd= model.encode(r)
    out_embs.append(embd)
    
out_embs = np.array(out_embs)
out_embs.shape

100%|██████████| 570/570 [00:07<00:00, 78.97it/s]

(570, 384)

In [ ]:
query = 'kashmir'

def search_query ( query):
    qy_emb = model.encode([query])
    sims=[]
    for e in tqdm(out_embs):
        sims.append(model.similarity(qy_emb, e).numpy()[0])
        
    df_ind = df_ind_mov[['id', 'title', 'description']].copy()
    df_ind.loc[:, 'sims']= np.array(sims)
    return df_ind.sort_values('sims', ascending=False)[:5]

In [ ]:
def search_similar( query ):
    qy_emb = model.encode([query])
    sims=[]
    for e in tqdm(out_embs):
        sims.append(model.similarity(qy_emb, e).numpy()[0])
        
    df_ind = df_ind_mov[['id', 'title', 'description']].copy()
    df_ind.loc[:, 'sims']= np.array(sims)
    return df_ind.sort_values('sims', ascending=False)[:5]

In [ ]:
search_similar("three college friends do a lot of fun")

  0%|          | 0/570 [00:00<?, ?it/s]

100%|██████████| 570/570 [00:00<00:00, 7167.47it/s]

,id,title,description,sims
434,tm61056,Dil Chahta Hai,Three inseparable childhood friends are just o...,0.456041
721,tm182125,Zindagi Na Milegi Dobara,Three friends who were inseparable in childhoo...,0.414460
5154,tm1213009,Dear Friend,Four close friends who live together in Bangal...,0.388510
972,tm185797,Fukrey,The paths of four dream-chasing college friend...,0.387179
316,tm142564,3 Idiots,Rascal. Joker. Dreamer. Genius... You've never...,0.363208

In [ ]:
cred = pd.read_csv("C:/Users/dbda.STUDENTSDC/Desktop/AAS/Nteflix/credits.csv")
cred

,person_id,id,name,character,role
0,3748,tm84618,Robert De Niro,Travis Bickle,ACTOR
1,14658,tm84618,Jodie Foster,Iris Steensma,ACTOR
2,7064,tm84618,Albert Brooks,Tom,ACTOR
3,3739,tm84618,Harvey Keitel,Matthew 'Sport' Higgins,ACTOR
4,48933,tm84618,Cybill Shepherd,Betsy,ACTOR
...,...,...,...,...,...
77796,736339,tm1059008,Adelaida Buscato,María Paz,ACTOR
77797,399499,tm1059008,Luz Stella Luengas,Karen Bayona,ACTOR
77798,373198,tm1059008,Inés Prieto,Fanny,ACTOR
77799,378132,tm1059008,Isabel Gaona,Cacica,ACTOR
77800,1950416,tm1059008,Julian Gaviria,NaN,DIRECTOR

In [ ]:
df_indian_mov = df[(df['production_countries'].str.contains('IN')) & (df['type']=='MOVIE') & (df['release_year'] >= 1980)]
all_ind_ids = list(df_indian_mov['id'].unique())
cred_ind = cred[cred['id'].isin(all_ind_ids)]
cred_ind.shape, cred.shape

((7209, 5), (77801, 5))

In [ ]:
# list(set(cred_ind['id']))
list(cred_ind['id'].unique())

['tm94651',
 'tm721687',
 'tm52815',
 'tm159912',
 'tm157603',
 'tm446654',
 'tm348735',
 'tm342996',
 'tm371359',
 'tm311264',
 'tm411457',
 'tm172482',
 'tm419052',
 'tm67635',
 'tm117873',
 'tm55100',
 'tm12876',
 'tm62176',
 'tm52871',
 'tm184326',
 'tm62385',
 'tm9898',
 'tm47530',
 'tm192301',
 'tm58893',
 'tm110160',
 'tm118438',
 'tm27601',
 'tm340430',
 'tm256669',
 'tm25389',
 'tm334788',
 'tm42397',
 'tm314602',
 'tm449775',
 'tm142564',
 'tm43399',
 'tm83786',
 'tm97544',
 'tm103732',
 'tm73058',
 'tm36475',
 'tm144345',
 'tm76835',
 'tm86051',
 'tm29269',
 'tm82765',
 'tm32885',
 'tm72587',
 'tm83175',
 'tm61056',
 'tm129763',
 'tm22540',
 'tm30170',
 'tm29731',
 'tm44530',
 'tm155761',
 'tm33067',
 'tm70222',
 'tm98975',
 'tm101609',
 'tm39557',
 'tm141117',
 'tm33729',
 'tm93004',
 'tm145243',
 'tm111226',
 'tm23441',
 'tm166293',
 'tm92977',
 'tm77348',
 'tm91323',
 'tm88366',
 'tm156575',
 'tm164389',
 'tm37945',
 'tm106625',
 'tm99450',
 'tm149209',
 'tm129971',
 'tm77863',
 'tm80455',
 'tm184732',
 'tm134407',
 'tm103133',
 'tm54147',
 'tm152724',
 'tm96168',
 'tm146887',
 'tm165809',
 'tm31335',
 'tm43179',
 'tm170169',
 'tm84316',
 'tm112235',
 'tm368679',
 'tm148041',
 'tm176297',
 'tm35652',
 'tm36636',
 'tm98475',
 'tm96595',
 'tm154802',
 'tm97982',
 'tm52176',
 'tm102848',
 'tm114504',
 'tm154375',
 'tm134140',
 'tm27484',
 'tm164591',
 'tm130301',
 'tm143510',
 'tm49865',
 'tm598375',
 'tm32915',
 'tm254052',
 'tm91125',
 'tm85689',
 'tm57586',
 'tm42831',
 'tm101540',
 'tm142153',
 'tm88343',
 'tm628693',
 'tm46867',
 'tm95507',
 'tm75544',
 'tm144263',
 'tm85369',
 'tm311516',
 'tm130999',
 'tm164353',
 'tm182125',
 'tm177258',
 'tm68436',
 'tm179451',
 'tm35700',
 'tm169053',
 'tm183037',
 'tm177958',
 'tm178106',
 'tm57610',
 'tm59372',
 'tm159593',
 'tm44615',
 'tm175909',
 'tm59289',
 'tm47171',
 'tm48239',
 'tm54371',
 'tm172883',
 'tm174518',
 'tm74031',
 'tm38013',
 'tm42306',
 'tm39606',
 'tm167241',
 'tm71992',
 'tm166810',
 'tm69915',
 'tm66725',
 'tm166740',
 'tm172353',
 'tm34746',
 'tm53360',
 'tm180532',
 'tm34142',
 'tm70652',
 'tm57256',
 'tm481620',
 'tm30278',
 'tm165932',
 'tm182026',
 'tm235979',
 'tm147913',
 'tm156811',
 'tm148910',
 'tm143363',
 'tm155291',
 'tm151927',
 'tm185797',
 'tm181092',
 'tm148457',
 'tm181550',
 'tm145627',
 'tm186161',
 'tm183002',
 'tm158302',
 'tm182322',
 'tm157062',
 'tm186054',
 'tm167342',
 'tm158980',
 'tm175753',
 'tm178513',
 'tm160034',
 'tm142630',
 'tm176481',
 'tm167107',
 'tm158546',
 'tm143299',
 'tm184511',
 'tm169054',
 'tm154729',
 'tm183805',
 'tm147908',
 'tm177224',
 'tm187118',
 'tm159296',
 'tm186408',
 'tm157783',
 'tm146144',
 'tm175364',
 'tm171891',
 'tm176900',
 'tm138280',
 'tm159094',
 'tm1194608',
 'tm157286',
 'tm179248',
 'tm242276',
 'tm150962',
 'tm137002',
 'tm234586',
 'tm244915',
 'tm218052',
 'tm138584',
 'tm239739',
 'tm200454',
 'tm241998',
 'tm208628',
 'tm208713',
 'tm219817',
 'tm201365',
 'tm233843',
 'tm197503',
 'tm233344',
 'tm240162',
 'tm211478',
 'tm272854',
 'tm233015',
 'tm193388',
 'tm540757',
 'tm207668',
 'tm233366',
 'tm245042',
 'tm227044',
 'tm245293',
 'tm211424',
 'tm134052',
 'tm232930',
 'tm219699',
 'tm246485',
 'tm201855',
 'tm217986',
 'tm215911',
 'tm247444',
 'tm66466',
 'tm340927',
 'tm232947',
 'tm246810',
 'tm242906',
 'tm421382',
 'tm234735',
 'tm233482',
 'tm221953',
 'tm423373',
 'tm464542',
 'tm307776',
 'tm366590',
 'tm371952',
 'tm317491',
 'tm419496',
 'tm326704',
 'tm365824',
 'tm307843',
 'tm313712',
 'tm417317',
 'tm307761',
 'tm313424',
 'tm409456',
 'tm439854',
 'tm340587',
 'tm421748',
 'tm307774',
 'tm307751',
 'tm353247',
 'tm363878',
 'tm372061',
 'tm320817',
 'tm327708',
 'tm307767',
 'tm432327',
 'tm409817',
 'tm244287',
 'tm372969',
 'tm326089',
 'tm445255',
 'tm852185',
 'tm360945',
 'tm445456',
 'tm244277',
 'tm368441',
 'tm309115',
 'tm449262',
 'tm321073',
 'tm413418',
 'tm443537',
 'tm422715',
 'tm244310',
 'tm430281',
 'tm456983',
 'tm319310',
 'tm431928',
 'tm324204',
 'tm445153',
 'tm369433',
 'tm368729',
 'tm138667',
 'tm432313',
 'tm444257',
 'tm319127',
 'tm347060',
 'tm332572',
 'tm411508',
 'tm374395',
 'tm369315',
 'tm345225',
 'tm814861',
 'tm363181',
 'tm246330',
 'tm426994',
 'tm364769',
 'tm442354',
 'tm312738',
 'tm368350',
 'tm327619',
 'tm242887',
 'tm411649',
 'tm328041',
 'tm469399',
 'tm350116',
 'tm358370',
 'tm404569',
 'tm367613',
 'tm450769',
 'tm153164',
 'tm430748',
 'tm444907',
 'tm336084',
 'tm420789',
 'tm450375',
 'tm919864',
 'tm831061',
 'tm475252',
 'tm283581',
 'tm425698',
 'tm857051',
 'tm678851',
 'tm493511',
 'tm458328',
 'tm495609',
 'tm848443',
 'tm319139',
 'tm467804',
 'tm451502',
 'tm844250',
 'tm366245',
 'tm948100',
 'tm933826',
 'tm464888',
 'tm918043',
 'tm450462',
 'tm848663',
 'tm462277',
 'tm494847',
 'tm837690',
 'tm858416',
 'tm675154',
 'tm460815',
 'tm856424',
 'tm455161',
 'tm373452',
 'tm426630',
 'tm483602',
 'tm886214',
 'tm455981',
 'tm834715',
 'tm477006',
 'tm677746',
 'tm492043',
 'tm976632',
 'tm857873',
 'tm921416',
 'tm455197',
 'tm459329',
 'tm919210',
 'tm851912',
 'tm912190',
 'tm468200',
 'tm893874',
 'tm423624',
 'tm840723',
 'tm898773',
 'tm511991',
 'tm849323',
 'tm428506',
 'tm946277',
 'tm973335',
 'tm847212',
 'tm850382',
 'tm464509',
 'tm859143',
 'tm821662',
 'tm810642',
 'tm950808',
 'tm431769',
 'tm851499',
 'tm849102',
 'tm810836',
 'tm818239',
 'tm469510',
 'tm926528',
 'tm854454',
 'tm473813',
 'tm908128',
 'tm882606',
 'tm115973',
 'tm431349',
 'tm881984',
 'tm935388',
 'tm894241',
 'tm831196',
 'tm940566',
 'tm484173',
 'tm919920',
 'tm478962',
 'tm813634',
 'tm828318',
 'tm373471',
 'tm493556',
 'tm816432',
 'tm828570',
 'tm435836',
 'tm483511',
 'tm838007',
 'tm848261',
 'tm835414',
 'tm832463',
 'tm472999',
 'tm863879',
 'tm475815',
 'tm854786',
 'tm973704',
 'tm847805',
 'tm814652',
 'tm477403',
 'tm863514',
 'tm439365',
 'tm944561',
 'tm466854',
 'tm845594',
 'tm463217',
 'tm838022',
 'tm468811',
 'tm373655',
 'tm852775',
 'tm461427',
 'tm471802',
 'tm922407',
 'tm924556',
 'tm893510',
 'tm510525',
 'tm679270',
 'tm885948',
 'tm476496',
 'tm461907',
 'tm1114639',
 'tm811954',
 'tm810873',
 'tm460199',
 'tm463762',
 'tm996762',
 'tm1117040',
 'tm949309',
 'tm1166046',
 'tm1227853',
 'tm1151272',
 'tm857461',
 'tm1217459',
 'tm1195561',
 'tm1086874',
 'tm996676',
 'tm1188818',
 'tm1221280',
 'tm1019885',
 'tm1030071',
 'tm1195032',
 'tm1138870',
 'tm1228963',
 'tm1213009',
 'tm473502',
 'tm1143898',
 'tm1031976',
 'tm876997',
 'tm833467',
 'tm1000619',
 'tm466544',
 'tm448707',
 'tm950444',
 'tm1127479',
 'tm858287',
 'tm990835',
 'tm1132325',
 'tm1073802',
 'tm949382',
 'tm1022912',
 'tm1025318',
 'tm1001095',
 'tm998033',
 'tm859256',
 'tm1024062',
 'tm1143258',
 'tm1025493',
 'tm1183542',
 'tm810657',
 'tm855340',
 'tm1033803',
 'tm1039168',
 'tm1172947',
 'tm856634',
 'tm963023',
 'tm1028026',
 'tm867681',
 'tm1173806',
 'tm1030241',
 'tm1073555',
 'tm1019865',
 'tm1027639',
 'tm869475',
 'tm1067260',
 'tm1142245',
 'tm1109843',
 'tm886193',
 'tm1022280',
 'tm998678',
 'tm1091284',
 'tm1036797',
 'tm1027177',
 'tm1115392',
 'tm1150727',
 'tm1091823',
 'tm1109080',
 'tm1004011',
 'tm987730',
 'tm988613',
 'tm1110241',
 'tm996479']

In [ ]:
actors = cred_ind[cred_ind['role']=='ACTOR']
dicrectors = cred_ind[cred_ind['role']=='DIRECTOR']

In [ ]:
movie_dic= []

for e in list(dicrectors['id'].unique()):
    # mov_id = list(actors[actors['id']])
    dic_ss = dicrectors[dicrectors['id']==e]
    movie_dic.append([e, ", ".join(list(dic_ss['name']))])

df_ind_dir = pd.DataFrame( movie_dic, columns=['id', 'Director'])
df_ind_dir

            id               Director
0      tm94651             Raj Khosla
1     tm721687          Vishnu Raghav
2      tm52815         Babbar Subhash
3     tm159912            Mukul Anand
4     tm157603            Indra Kumar
..         ...                    ...
535  tm1004011        Stanley D'Costa
536   tm987730         Renuka Shahane
537   tm988613         Subhash Kapoor
538  tm1110241  Nithin Renji Panicker
539   tm996479        Taranveer Singh

[540 rows x 2 columns]

In [ ]:
movie_actor = []

for e in list(actors['id'].unique()):
    # mov_id = list(actors[actors['id']])
    ss = actors[actors['id']==e]
    movie_actor.append([e, ", ".join(list(ss['name']))])

df_ind_act = pd.DataFrame( movie_actor, columns=['id', 'star cast'])
df_ind_act

            id                                          star cast
0      tm94651  Amitabh Bachchan, Shatrughan Sinha, Zeenat Ama...
1     tm721687  Tovino Thomas, Keerthy Suresh, Kottayam Ramesh...
2      tm52815  Mithun Chakraborty, Kim, Rajesh Khanna, Om Shi...
3     tm159912  Amitabh Bachchan, Mithun Chakraborty, Madhavi,...
4     tm157603  Aamir Khan, Madhuri Dixit, Saeed Jaffrey, Anup...
..         ...                                                ...
546  tm1004011  Sooraj Pancholi, Isabelle Kaif, Sammy Jonas He...
547   tm987730  Kajol, Tanvi Azmi, Mithila Palkar, Kunaal Roy ...
548   tm988613  Richa Chadha, Saurabh Shukla, Manav Kaul, Aksh...
549  tm1110241  Suresh Gopi, Renji Panicker, Rajesh Sharma, Mu...
550   tm996479  Jhataleka Malhotra, Anmol Thakeria Dhillon, Ni...

[551 rows x 2 columns]