In [34]:
from transformers import pipeline
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [35]:
data = {"Actors":['Brad Pitt', "Leo Di Caprio", "George Clooney"], "Number of Movies": ['87','53','69']}
table = pd.DataFrame.from_dict(data)
table
type(table)

pandas.core.frame.DataFrame

In [36]:
# Use a pipeline as a high-level helper
from transformers import pipeline

tqa = pipeline("table-question-answering", model="google/tapas-base-finetuned-wtq")

Device set to use cpu

In [37]:
question = "how many movies does brad pitt have ?"
print(tqa(table = table, query=question)['cells'][0])

87

In [38]:
cars2018 = pd.read_csv("D:\Machine Learning\Datasets\cars2018.csv")
cars2018.shape
cars2018.columns
cars2018['Model ID'] = cars2018['Model']+ " - " + cars2018[ 'Model Index'].astype(str)
cars_ss = cars2018[["Model ID", 'MPG']]
cars_ss.head()

                  Model ID  MPG
0           Acura NSX - 57   21
1      ALFA ROMEO 4C - 410   28
2         Audi R8 AWD - 65   17
3         Audi R8 RWD - 71   18
4  Audi R8 Spyder AWD - 66   17

In [39]:
cars_ss = cars2018[['Model ID','MPG','Displacement','Recommended Fuel']]
cars_ss = cars_ss.head(50)
cars_ss = cars_ss.astype(str)
cars_ss['Details'] = "MPG: " + cars_ss['MPG'] + ", Displacement:" + cars_ss['Displacement'] + ", Recommended Fuel:" + cars_ss['Recommended Fuel']
cars_ss.to_csv("D:\Machine Learning\Datasets\cars_ss.csv",index=False)

In [40]:
cars_ss = pd.read_csv("D:\Machine Learning\Datasets\cars_ss.csv")
type(cars_ss.columns)
# type(cars_ss)
cars_ss.tail()

,Model ID,MPG,Displacement,Recommended Fuel,Details
45,Mercedes-Benz AMG GT (coupe) - 191,18,4.0,Premium Unleaded Required,"MPG: 18, Displacement:4.0, Recommended Fuel:Pr..."
46,Mercedes-Benz AMG GT (roadster) - 234,18,4.0,Premium Unleaded Required,"MPG: 18, Displacement:4.0, Recommended Fuel:Pr..."
47,Mercedes-Benz AMG GT C (coupe) - 192,17,4.0,Premium Unleaded Required,"MPG: 17, Displacement:4.0, Recommended Fuel:Pr..."
48,Mercedes-Benz AMG GT C (roadster) - 235,17,4.0,Premium Unleaded Required,"MPG: 17, Displacement:4.0, Recommended Fuel:Pr..."
49,Mercedes-Benz AMG GT R (coupe) - 194,17,4.0,Premium Unleaded Required,"MPG: 17, Displacement:4.0, Recommended Fuel:Pr..."

In [41]:
question = "can u Give me the details of Audi R8 RWD - 71 ?"
# question = "how many movies does brad pitt have ?"
print(tqa(table = cars_ss, query=question)['cells'])

TypeError: expected string or bytes-like object, got 'int'

In [ ]:
import gradio as gr
from io import StringIO
def answer(question, file):
    with open(file, 'r') as readfile:
        ctx = readfile.read().rstrip()
    csvStringIO = StringIO(ctx)
    df = pd.read_csv(csvStringIO, sep=",")
    df = df.astype('str')
    response = tqa(table=df, query= question)['cells'][0]
    return response

In [ ]:
demo = gr.Interface(
    fn = answer,
    inputs = ['text',gr.File(label="Information file")],
    outputs=["text"]
)
demo.launch()

* Running on local URL:  http://127.0.0.1:7860
* To create a public link, set `share=True` in `launch()`.

d:\Anaconda\envs\hf\Lib\site-packages\transformers\models\tapas\tokenization_tapas.py:2700: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  text = normalize_for_match(row[col_index].text)
d:\Anaconda\envs\hf\Lib\site-packages\transformers\models\tapas\tokenization_tapas.py:1494: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  cell = row[col_index]