In [6]:
import mlxtend
import pandas as pd
from sklearn.model_selection import train_test_split
from mlxtend.frequent_patterns import apriori
import warnings
warnings.filterwarnings('ignore')

In [7]:
fp_df = pd.read_csv('G:/My Drive/#myCDACfiles/MachineLearning/Datasets/Faceplate.csv')
fp_df.head()

   Transaction  Red  White  Blue  Orange  Green  Yellow
0            1    1      1     0       0      1       0
1            2    0      1     0       1      0       0
2            3    0      1     1       0      0       0
3            4    1      1     0       1      0       0
4            5    1      0     1       0      0       0

In [8]:
from mlxtend.frequent_patterns import association_rules

In [10]:
fp_df=fp_df.astype(bool)
itemsets = apriori(fp_df, min_support=0.2, use_colnames=True)
rules = association_rules(itemsets, metric="confidence", min_threshold=0.6)
rules = rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']]
rules = rules.sort_values(['lift', 'confidence'], ascending=[False, False])
rules

,antecedents,consequents,support,confidence,lift
37,(Green),"(White, Red)",0.2,1.000000,2.500000
43,"(Green, Transaction)","(White, Red)",0.2,1.000000,2.500000
45,(Green),"(White, Transaction, Red)",0.2,1.000000,2.500000
11,(Green),(Red),0.2,1.000000,1.666667
23,"(Green, Transaction)",(Red),0.2,1.000000,1.666667
25,(Green),"(Transaction, Red)",0.2,1.000000,1.666667
35,"(White, Green)",(Red),0.2,1.000000,1.666667
39,"(White, Green, Transaction)",(Red),0.2,1.000000,1.666667
42,"(White, Green)","(Transaction, Red)",0.2,1.000000,1.666667
13,(Orange),(White),0.2,1.000000,1.428571
14,(Green),(White),0.2,1.000000,1.428571
30,"(Transaction, Orange)",(White),0.2,1.000000,1.428571
31,(Orange),"(White, Transaction)",0.2,1.000000,1.428571
33,"(Green, Transaction)",(White),0.2,1.000000,1.428571
34,(Green),"(White, Transaction)",0.2,1.000000,1.428571
36,"(Green, Red)",(White),0.2,1.000000,1.428571
41,"(Green, Transaction, Red)",(White),0.2,1.000000,1.428571
44,"(Green, Red)","(White, Transaction)",0.2,1.000000,1.428571
9,(Blue),(Red),0.4,0.666667,1.111111
10,(Red),(Blue),0.4,0.666667,1.111111
18,"(Blue, Transaction)",(Red),0.4,0.666667,1.111111
20,"(Transaction, Red)",(Blue),0.4,0.666667,1.111111
21,(Blue),"(Transaction, Red)",0.4,0.666667,1.111111
22,(Red),"(Blue, Transaction)",0.4,0.666667,1.111111
1,(Red),(Transaction),0.6,1.000000,1.000000
2,(White),(Transaction),0.7,1.000000,1.000000
4,(Blue),(Transaction),0.6,1.000000,1.000000
6,(Orange),(Transaction),0.2,1.000000,1.000000
7,(Green),(Transaction),0.2,1.000000,1.000000
15,"(White, Red)",(Transaction),0.4,1.000000,1.000000
19,"(Blue, Red)",(Transaction),0.4,1.000000,1.000000
24,"(Green, Red)",(Transaction),0.2,1.000000,1.000000
26,"(White, Blue)",(Transaction),0.4,1.000000,1.000000
29,"(White, Orange)",(Transaction),0.2,1.000000,1.000000
32,"(White, Green)",(Transaction),0.2,1.000000,1.000000
38,"(White, Blue, Red)",(Transaction),0.2,1.000000,1.000000
40,"(White, Green, Red)",(Transaction),0.2,1.000000,1.000000
3,(Transaction),(White),0.7,0.700000,1.000000
0,(Transaction),(Red),0.6,0.600000,1.000000
5,(Transaction),(Blue),0.6,0.600000,1.000000
8,(Red),(White),0.4,0.666667,0.952381
12,(Blue),(White),0.4,0.666667,0.952381
16,"(Transaction, Red)",(White),0.4,0.666667,0.952381
17,(Red),"(White, Transaction)",0.4,0.666667,0.952381
27,"(Blue, Transaction)",(White),0.4,0.666667,0.952381
28,(Blue),"(White, Transaction)",0.4,0.666667,0.952381