In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,root_mean_squared_error,mean_absolute_error
import os

In [3]:
os.chdir('D:\Machine Learning\Datasets')

In [4]:

### Ploynomial Regression with degree 2
pizza = pd.read_csv("pizza.csv")
X, y = pizza[['Promote']], pizza['Sales']
poly = PolynomialFeatures(degree=2, include_bias=False).set_output(transform="pandas")
X_poly = poly.fit_transform(X)
lr = LinearRegression()
lr.fit(X_poly, y)
lr.intercept_, lr.coef_
# Sales = -18.275 + 24.801 * Promote + 0.013 * Promote^2

(np.float64(-18.274917416646076), array([ 2.48006959e+01, -1.30947333e-02]))

In [5]:
pizza.head()

   Promote  Sales
0       23    554
1       56   1339
2       34    815
3       25    609
4       67   1600

In [ ]:
boston = pd.read_csv("boston.csv")
boston

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [7]:
poly = PolynomialFeatures(degree=2, include_bias=False).set_output(transform="pandas")
X_test_poly = poly.fit_transform(pizza)
X_test_poly

    Promote   Sales  Promote^2  Promote Sales    Sales^2
0      23.0   554.0      529.0        12742.0   306916.0
1      56.0  1339.0     3136.0        74984.0  1792921.0
2      34.0   815.0     1156.0        27710.0   664225.0
3      25.0   609.0      625.0        15225.0   370881.0
4      67.0  1600.0     4489.0       107200.0  2560000.0
5      82.0  2000.0     6724.0       164000.0  4000000.0
6      46.0  1000.0     2116.0        46000.0  1000000.0
7      14.0   300.0      196.0         4200.0    90000.0
8       6.0   150.0       36.0          900.0    22500.0
9      47.0  1150.0     2209.0        54050.0  1322500.0
10     52.0  1200.0     2704.0        62400.0  1440000.0
11     88.0  2000.0     7744.0       176000.0  4000000.0
12     71.0  1750.0     5041.0       124250.0  3062500.0
13     78.0  2000.0     6084.0       156000.0  4000000.0
14     66.0  1500.0     4356.0        99000.0  2250000.0
15     44.0  1000.0     1936.0        44000.0  1000000.0
16     68.0  1600.0     4624.0       108800.0  2560000.0
17     90.0  2000.0     8100.0       180000.0  4000000.0
18     22.0   550.0      484.0        12100.0   302500.0

In [8]:
boston.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [9]:
X=boston.drop('medv',axis=1)
y=boston['medv']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [10]:
poly = PolynomialFeatures(degree=2, include_bias=False).set_output(transform="pandas")
X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.fit_transform(X_test)

lr = LinearRegression()
lr.fit(X_train_poly, y_train)
y_pred=lr.predict(X_test_poly)
lr.intercept_, lr.coef_
mean_absolute_error(y_test,y_pred)

2.5748356276457205

In [11]:
poly = PolynomialFeatures(degree=3, include_bias=False).set_output(transform="pandas")
X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.fit_transform(X_test)

lr = LinearRegression()
lr.fit(X_train_poly, y_train)
y_pred=lr.predict(X_test_poly)
lr.intercept_, lr.coef_
mean_absolute_error(y_test,y_pred)

190.53447967061516

In [12]:
poly = PolynomialFeatures(degree=4, include_bias=False).set_output(transform="pandas")
X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.fit_transform(X_test)

lr = LinearRegression()
lr.fit(X_train_poly, y_train)
y_pred=lr.predict(X_test_poly)
lr.intercept_, lr.coef_
mean_absolute_error(y_test,y_pred)

28.925543678597222

## Housing dataset

In [13]:
housing=pd.read_csv('Housing.csv')

In [14]:
housing

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,61000.0,6360,2,1,1,yes,no,no,no,no,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...
541,91500.0,4800,3,2,4,yes,yes,no,no,yes,0,no
542,94000.0,6000,3,2,4,yes,no,no,no,yes,0,no
543,103000.0,6000,3,2,4,yes,yes,no,no,yes,1,no
544,105000.0,6000,3,2,2,yes,yes,no,no,yes,1,no
545,105000.0,6000,3,1,2,yes,no,no,no,yes,1,no

In [15]:
from sklearn.preprocessing import OneHotEncoder

In [17]:
cat_hous=housing[housing.columns[housing.dtypes==object]] # seperating catogorical data
num_hous=housing[housing.columns[housing.dtypes!=object]]
ohe=OneHotEncoder(drop='first',sparse_output=False).set_output(transform='pandas') # one hot encoder
ohe_house=ohe.fit_transform(cat_hous) # cat to 1,0
house=pd.concat([num_hous,ohe_house],axis=1) # row-wise concat
X,y=house.drop('price',axis=1),house['price']

In [ ]:
X

     lotsize  bedrooms  bathrms  ...  gashw_yes  airco_yes  prefarea_yes
0       5850         3        1  ...        0.0        0.0           0.0
1       4000         2        1  ...        0.0        0.0           0.0
2       3060         3        1  ...        0.0        0.0           0.0
3       6650         3        1  ...        0.0        0.0           0.0
4       6360         2        1  ...        0.0        0.0           0.0
..       ...       ...      ...  ...        ...        ...           ...
541     4800         3        2  ...        0.0        1.0           0.0
542     6000         3        2  ...        0.0        1.0           0.0
543     6000         3        2  ...        0.0        1.0           0.0
544     6000         3        2  ...        0.0        1.0           0.0
545     6000         3        1  ...        0.0        1.0           0.0

[546 rows x 11 columns]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
lr = LinearRegression()
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)
mean_absolute_error(y_test,y_pred)

11463.13592249464

In [ ]:
poly = PolynomialFeatures(degree=0, include_bias=True).set_output(transform="pandas")
X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.fit_transform(X_test)

lr = LinearRegression()
lr.fit(X_train_poly, y_train)
y_pred=lr.predict(X_test_poly)
lr.intercept_, lr.coef_
mean_absolute_error(y_test,y_pred)

20312.572894078392

In [ ]:
X_train_poly

       1
93   1.0
335  1.0
412  1.0
473  1.0
237  1.0
..   ...
71   1.0
106  1.0
270  1.0
435  1.0
102  1.0

[436 rows x 1 columns]

In [ ]:
poly = PolynomialFeatures(degree=2, include_bias=False).set_output(transform="pandas")
X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.fit_transform(X_test)

lr = LinearRegression()
lr.fit(X_train_poly, y_train)
y_pred=lr.predict(X_test_poly)
lr.intercept_, lr.coef_
mean_absolute_error(y_test,y_pred)

13985.316930804354

In [ ]:
poly = PolynomialFeatures(degree=3, include_bias=False).set_output(transform="pandas")
X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.fit_transform(X_test)

lr = LinearRegression()
lr.fit(X_train_poly, y_train)
y_pred=lr.predict(X_test_poly)
lr.intercept_, lr.coef_
mean_absolute_error(y_test,y_pred)

18851.610459877236

In [ ]:
# Column Transformer
from sklearn.compose import ColumnTransformer

In [ ]:
ohe=OneHotEncoder(drop='first',sparse_output=False).set_output(transform='pandas') # one hot encoder
col_trnf=ColumnTransformer([('OHE',ohe,list(housing.columns[housing.dtypes==object]))],remainder='passthrough',verbose_feature_names_out=True)
col_trnf=col_trnf.set_output(transform='pandas')
col_trnf.fit_transform(housing)

     OHE__driveway_yes  ...  remainder__garagepl
0                  1.0  ...                    1
1                  1.0  ...                    0
2                  1.0  ...                    0
3                  1.0  ...                    0
4                  1.0  ...                    0
..                 ...  ...                  ...
541                1.0  ...                    0
542                1.0  ...                    0
543                1.0  ...                    1
544                1.0  ...                    1
545                1.0  ...                    1

[546 rows x 12 columns]