In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures , OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,root_mean_squared_error,mean_absolute_error
import os
from tqdm import tqdm

In [2]:
os.chdir('D:\Machine Learning\Datasets')

In [6]:
df = pd.read_csv("boston.csv")
df

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [7]:
from sklearn.compose import make_column_selector
ohe=OneHotEncoder(drop='first',sparse_output=False).set_output(transform='pandas') # one hot encoder
col_trnf=ColumnTransformer([('OHE',ohe,make_column_selector(dtype_include=object))],remainder='passthrough',verbose_feature_names_out=True)
col_trnf=col_trnf.set_output(transform='pandas')
X=col_trnf.fit_transform(df)

In [8]:
from sklearn.linear_model import Lasso

In [10]:
X=df.drop('medv',axis=1)
y=df['medv']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [11]:
alphas = np.linspace(.001,15,30)
scores=[]
for a in alphas:
    model=Lasso(alpha=a)
    model.fit(X_train,y_train)
    y_pred=model.predict(X_test)
    scores.append([a,mean_absolute_error(y_test,y_pred)])
df_scores=pd.DataFrame(scores,columns=['alpha','score'])
df_scores.sort_values('score')

        alpha     score
0    0.001000  3.162567
1    0.518207  3.403493
2    1.035414  3.678579
3    1.552621  3.962561
4    2.069828  4.129482
5    2.587034  4.249978
6    3.104241  4.335047
7    3.621448  4.404345
8    4.138655  4.477113
9    4.655862  4.482810
10   5.173069  4.488721
11   5.690276  4.494653
12   6.207483  4.500591
13   6.724690  4.507851
14   7.241897  4.515112
21  10.862345  4.520463
22  11.379552  4.521109
15   7.759103  4.522372
23  11.896759  4.522907
20  10.345138  4.523204
24  12.413966  4.526517
19   9.827931  4.527291
16   8.276310  4.531159
18   9.310724  4.531380
25  12.931172  4.533236
17   8.793517  4.535847
26  13.448379  4.542003
27  13.965586  4.550819
28  14.482793  4.559759
29  15.000000  4.569910