In [86]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures , OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,root_mean_squared_error,mean_absolute_error
import os
from tqdm import tqdm

In [87]:
os.chdir('D:\Machine Learning\Datasets')

In [88]:
df=pd.read_csv('Housing.csv')

In [89]:
from sklearn.compose import make_column_selector
ohe=OneHotEncoder(drop='first',sparse_output=False).set_output(transform='pandas') # one hot encoder
col_trnf=ColumnTransformer([('OHE',ohe,make_column_selector(dtype_include=object))],remainder='passthrough',verbose_feature_names_out=True)
col_trnf=col_trnf.set_output(transform='pandas')
X=col_trnf.fit_transform(df)

# Ridge

In [90]:
from sklearn.linear_model import Ridge

In [91]:
boston = pd.read_csv("boston.csv")
boston

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [92]:
X=boston.drop('medv',axis=1)
y=boston['medv']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [93]:
alphas = [0.001, 0.01, 0.1, 1, 10, 100, 1000]
results=[]

In [94]:
# train ridge model with different alpha values
from sklearn.metrics import mean_squared_error


for alpha in alphas:
    model=Ridge(alpha=alpha)
    model.fit(X_train,y_train)

    #Predictions
    y_pred_train=model.predict(X_train)
    y_pred_test=model.predict(X_test)

   # Metrics
    train_mse = mean_squared_error(y_train, y_pred_train)
    test_mse = mean_squared_error(y_test, y_pred_test)
    train_r2 = r2_score(y_train, y_pred_train)
    test_r2 = r2_score(y_test, y_pred_test)
    
    results.append({
        'alpha': alpha,
        'coef': model.coef_[0],
        'intercept': model.intercept_,
        'train_mse': train_mse,
        'test_mse': test_mse,
        'train_r2': train_r2,
        'test_r2': test_r2
    })
    
    print(f"Alpha: {alpha:7.3f} | Coef: {model.coef_[0]:6.3f} | "
          f"Intercept: {model.intercept_:6.3f} | "
          f"Train MSE: {train_mse:6.3f} | Test MSE: {test_mse:6.3f}")

Alpha:   0.001 | Coef: -0.133 | Intercept: 31.621 | Train MSE: 22.545 | Test MSE: 21.518
Alpha:   0.010 | Coef: -0.133 | Intercept: 31.534 | Train MSE: 22.546 | Test MSE: 21.524
Alpha:   0.100 | Coef: -0.133 | Intercept: 30.735 | Train MSE: 22.551 | Test MSE: 21.585
Alpha:   1.000 | Coef: -0.128 | Intercept: 26.765 | Train MSE: 22.715 | Test MSE: 22.044
Alpha:  10.000 | Coef: -0.127 | Intercept: 24.976 | Train MSE: 23.211 | Test MSE: 22.695
Alpha: 100.000 | Coef: -0.130 | Intercept: 36.100 | Train MSE: 24.829 | Test MSE: 23.468
Alpha: 1000.000 | Coef: -0.117 | Intercept: 39.596 | Train MSE: 29.511 | Test MSE: 27.100

Hyperparameter Tuning

In [95]:
alphas = [0.001, 0.01, 0.1, 1, 1.5,2.5,5,10]
scores=[]
for alpha in alphas:
    model=Ridge(alpha=alpha)
    model.fit(X_train,y_train)
        #Predictions
    y_pred=model.predict(X_test)
    scores.append([alpha,mean_absolute_error(y_test,y_pred)])
df_scores=pd.DataFrame(scores,columns=['alpha','score'])
df_scores.sort_values('score')

    alpha     score
2   0.100  3.162397
1   0.010  3.162624
0   0.001  3.162698
3   1.000  3.178539
4   1.500  3.189260
5   2.500  3.204128
6   5.000  3.227276
7  10.000  3.249170

Housing_dataset

In [96]:
housing=pd.read_csv('Housing.csv')

In [97]:
# column transformer
cat_hous=housing[housing.columns[housing.dtypes==object]] # seperating catogorical data
num_hous=housing[housing.columns[housing.dtypes!=object]]
ohe=OneHotEncoder(drop='first',sparse_output=False).set_output(transform='pandas') # one hot encoder
ohe_house=ohe.fit_transform(cat_hous) # cat to 1,0
house=pd.concat([num_hous,ohe_house],axis=1) # row-wise concat
X,y=house.drop('price',axis=1),house['price']

In [107]:
# train-test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
np.linspace(.001,15,30)

array([1.00000000e-03, 5.18206897e-01, 1.03541379e+00, 1.55262069e+00,
       2.06982759e+00, 2.58703448e+00, 3.10424138e+00, 3.62144828e+00,
       4.13865517e+00, 4.65586207e+00, 5.17306897e+00, 5.69027586e+00,
       6.20748276e+00, 6.72468966e+00, 7.24189655e+00, 7.75910345e+00,
       8.27631034e+00, 8.79351724e+00, 9.31072414e+00, 9.82793103e+00,
       1.03451379e+01, 1.08623448e+01, 1.13795517e+01, 1.18967586e+01,
       1.24139655e+01, 1.29311724e+01, 1.34483793e+01, 1.39655862e+01,
       1.44827931e+01, 1.50000000e+01])

In [108]:
alphas = np.linspace(.001,15,30)
scores=[]
for a in alphas:
    model=Ridge(alpha=a)
    model.fit(X_train,y_train)
    y_pred=model.predict(X_test)
    scores.append([a,mean_absolute_error(y_test,y_pred)])
df_scores=pd.DataFrame(scores,columns=['alpha','score'])
df_scores.sort_values('score')

        alpha         score
7    3.621448  11462.396390
8    4.138655  11462.418004
9    4.655862  11462.875243
6    3.104241  11463.351288
10   5.173069  11464.669465
11   5.690276  11466.809072
5    2.587034  11468.848793
12   6.207483  11469.034580
13   6.724690  11471.335969
4    2.069828  11475.110378
14   7.241897  11475.232484
15   7.759103  11479.324512
3    1.552621  11481.934082
16   8.276310  11483.352824
17   8.793517  11487.319011
2    1.035414  11489.378929
18   9.310724  11491.224607
19   9.827931  11495.071097
1    0.518207  11497.609271
20  10.345138  11499.212937
21  10.862345  11504.576762
0    0.001000  11507.081912
22  11.379552  11510.063087
23  11.896759  11515.479978
24  12.413966  11520.828862
25  12.931172  11526.111134
26  13.448379  11531.858826
27  13.965586  11537.592646
28  14.482793  11543.257020
29  15.000000  11548.853402

In [109]:
# auto generate alphas values
np.arange(0.001,15,.05)

array([1.0000e-03, 5.1000e-02, 1.0100e-01, 1.5100e-01, 2.0100e-01,
       2.5100e-01, 3.0100e-01, 3.5100e-01, 4.0100e-01, 4.5100e-01,
       5.0100e-01, 5.5100e-01, 6.0100e-01, 6.5100e-01, 7.0100e-01,
       7.5100e-01, 8.0100e-01, 8.5100e-01, 9.0100e-01, 9.5100e-01,
       1.0010e+00, 1.0510e+00, 1.1010e+00, 1.1510e+00, 1.2010e+00,
       1.2510e+00, 1.3010e+00, 1.3510e+00, 1.4010e+00, 1.4510e+00,
       1.5010e+00, 1.5510e+00, 1.6010e+00, 1.6510e+00, 1.7010e+00,
       1.7510e+00, 1.8010e+00, 1.8510e+00, 1.9010e+00, 1.9510e+00,
       2.0010e+00, 2.0510e+00, 2.1010e+00, 2.1510e+00, 2.2010e+00,
       2.2510e+00, 2.3010e+00, 2.3510e+00, 2.4010e+00, 2.4510e+00,
       2.5010e+00, 2.5510e+00, 2.6010e+00, 2.6510e+00, 2.7010e+00,
       2.7510e+00, 2.8010e+00, 2.8510e+00, 2.9010e+00, 2.9510e+00,
       3.0010e+00, 3.0510e+00, 3.1010e+00, 3.1510e+00, 3.2010e+00,
       3.2510e+00, 3.3010e+00, 3.3510e+00, 3.4010e+00, 3.4510e+00,
       3.5010e+00, 3.5510e+00, 3.6010e+00, 3.6510e+00, 3.7010e+00,
       3.7510e+00, 3.8010e+00, 3.8510e+00, 3.9010e+00, 3.9510e+00,
       4.0010e+00, 4.0510e+00, 4.1010e+00, 4.1510e+00, 4.2010e+00,
       4.2510e+00, 4.3010e+00, 4.3510e+00, 4.4010e+00, 4.4510e+00,
       4.5010e+00, 4.5510e+00, 4.6010e+00, 4.6510e+00, 4.7010e+00,
       4.7510e+00, 4.8010e+00, 4.8510e+00, 4.9010e+00, 4.9510e+00,
       5.0010e+00, 5.0510e+00, 5.1010e+00, 5.1510e+00, 5.2010e+00,
       5.2510e+00, 5.3010e+00, 5.3510e+00, 5.4010e+00, 5.4510e+00,
       5.5010e+00, 5.5510e+00, 5.6010e+00, 5.6510e+00, 5.7010e+00,
       5.7510e+00, 5.8010e+00, 5.8510e+00, 5.9010e+00, 5.9510e+00,
       6.0010e+00, 6.0510e+00, 6.1010e+00, 6.1510e+00, 6.2010e+00,
       6.2510e+00, 6.3010e+00, 6.3510e+00, 6.4010e+00, 6.4510e+00,
       6.5010e+00, 6.5510e+00, 6.6010e+00, 6.6510e+00, 6.7010e+00,
       6.7510e+00, 6.8010e+00, 6.8510e+00, 6.9010e+00, 6.9510e+00,
       7.0010e+00, 7.0510e+00, 7.1010e+00, 7.1510e+00, 7.2010e+00,
       7.2510e+00, 7.3010e+00, 7.3510e+00, 7.4010e+00, 7.4510e+00,
       7.5010e+00, 7.5510e+00, 7.6010e+00, 7.6510e+00, 7.7010e+00,
       7.7510e+00, 7.8010e+00, 7.8510e+00, 7.9010e+00, 7.9510e+00,
       8.0010e+00, 8.0510e+00, 8.1010e+00, 8.1510e+00, 8.2010e+00,
       8.2510e+00, 8.3010e+00, 8.3510e+00, 8.4010e+00, 8.4510e+00,
       8.5010e+00, 8.5510e+00, 8.6010e+00, 8.6510e+00, 8.7010e+00,
       8.7510e+00, 8.8010e+00, 8.8510e+00, 8.9010e+00, 8.9510e+00,
       9.0010e+00, 9.0510e+00, 9.1010e+00, 9.1510e+00, 9.2010e+00,
       9.2510e+00, 9.3010e+00, 9.3510e+00, 9.4010e+00, 9.4510e+00,
       9.5010e+00, 9.5510e+00, 9.6010e+00, 9.6510e+00, 9.7010e+00,
       9.7510e+00, 9.8010e+00, 9.8510e+00, 9.9010e+00, 9.9510e+00,
       1.0001e+01, 1.0051e+01, 1.0101e+01, 1.0151e+01, 1.0201e+01,
       1.0251e+01, 1.0301e+01, 1.0351e+01, 1.0401e+01, 1.0451e+01,
       1.0501e+01, 1.0551e+01, 1.0601e+01, 1.0651e+01, 1.0701e+01,
       1.0751e+01, 1.0801e+01, 1.0851e+01, 1.0901e+01, 1.0951e+01,
       1.1001e+01, 1.1051e+01, 1.1101e+01, 1.1151e+01, 1.1201e+01,
       1.1251e+01, 1.1301e+01, 1.1351e+01, 1.1401e+01, 1.1451e+01,
       1.1501e+01, 1.1551e+01, 1.1601e+01, 1.1651e+01, 1.1701e+01,
       1.1751e+01, 1.1801e+01, 1.1851e+01, 1.1901e+01, 1.1951e+01,
       1.2001e+01, 1.2051e+01, 1.2101e+01, 1.2151e+01, 1.2201e+01,
       1.2251e+01, 1.2301e+01, 1.2351e+01, 1.2401e+01, 1.2451e+01,
       1.2501e+01, 1.2551e+01, 1.2601e+01, 1.2651e+01, 1.2701e+01,
       1.2751e+01, 1.2801e+01, 1.2851e+01, 1.2901e+01, 1.2951e+01,
       1.3001e+01, 1.3051e+01, 1.3101e+01, 1.3151e+01, 1.3201e+01,
       1.3251e+01, 1.3301e+01, 1.3351e+01, 1.3401e+01, 1.3451e+01,
       1.3501e+01, 1.3551e+01, 1.3601e+01, 1.3651e+01, 1.3701e+01,
       1.3751e+01, 1.3801e+01, 1.3851e+01, 1.3901e+01, 1.3951e+01,
       1.4001e+01, 1.4051e+01, 1.4101e+01, 1.4151e+01, 1.4201e+01,
       1.4251e+01, 1.4301e+01, 1.4351e+01, 1.4401e+01, 1.4451e+01,
       1.4501e+01, 1.4551e+01, 1.4601e+01, 1.4651e+01, 1.4701e+01,
       1.4751e+01, 1.4801e+01, 1.4851e+01, 1.4901e+01, 1.4951e+01])

In [ ]:
np.linspace(.001,1.5,25)

array([1.00000000e-03, 6.34583333e-02, 1.25916667e-01, 1.88375000e-01,
       2.50833333e-01, 3.13291667e-01, 3.75750000e-01, 4.38208333e-01,
       5.00666667e-01, 5.63125000e-01, 6.25583333e-01, 6.88041667e-01,
       7.50500000e-01, 8.12958333e-01, 8.75416667e-01, 9.37875000e-01,
       1.00033333e+00, 1.06279167e+00, 1.12525000e+00, 1.18770833e+00,
       1.25016667e+00, 1.31262500e+00, 1.37508333e+00, 1.43754167e+00,
       1.50000000e+00])

In [110]:
# Salraies

In [119]:
sal=pd.read_csv('Exp_salaries.csv')
sal

,Salary,Years_Previous_Experience,Years Employed,Years_Education,Gender,Department,Number_Supervised
0,32782,1,0,7,Male,A,0
1,32920,3,15,9,Female,A,4
2,29548,6,5,1,Male,A,0
3,39828,6,18,5,Female,A,5
4,31528,11,3,3,Male,A,6
5,38985,7,18,9,Male,A,5
6,41889,16,22,7,Male,A,7
7,38791,4,21,5,Male,A,9
8,28985,1,0,4,Female,A,4
9,24749,2,6,0,Female,A,1
10,35467,6,3,6,Female,B,3
11,35468,5,9,4,Female,B,5
12,29876,0,2,3,Female,B,5
13,43674,9,6,4,Male,B,2
14,36431,4,9,4,Female,B,2
15,26578,6,0,2,Female,B,2
16,36571,1,6,4,Male,B,2
17,56326,3,12,8,Male,B,6
18,23654,0,0,0,Female,C,2
19,36578,4,4,8,Male,C,8
20,37548,9,19,4,Male,C,6
21,53234,0,25,6,Male,C,3
22,54679,3,20,6,Female,C,4
23,47536,5,15,6,Male,C,4
24,31425,6,7,5,Female,C,6
25,65487,0,27,12,Female,D,44
26,46184,3,20,4,Male,D,1
27,54899,5,12,8,Female,D,0
28,34869,5,7,4,Female,D,1
29,35487,2,8,2,Female,D,2
30,26548,1,5,0,Male,D,2
31,34231,2,6,6,Male,D,3
32,39331,3,9,6,Female,D,1
33,36512,6,6,4,Female,D,2
34,68425,2,25,12,Male,D,1
35,36487,5,6,2,Male,D,3
36,34632,4,5,4,Male,D,0
37,46211,5,14,6,Female,D,5
38,51698,6,18,6,Male,D,1
39,69246,3,22,10,Male,D,45
40,48695,19,6,8,Male,D,40
41,34987,6,9,2,Female,D,3
42,35631,4,6,4,Male,D,2
43,39743,6,9,5,Female,D,1
44,41255,4,9,6,Male,D,4
45,26452,3,1,2,Female,D,0

In [123]:
cat_sal=sal[sal.columns[sal.dtypes==object]]
num_sal=sal[sal.columns[sal.dtypes==int]]
ohe=OneHotEncoder(drop='first',sparse_output=False).set_output(transform='pandas')
one_sal=ohe.fit_transform(cat_sal)
sal=pd.concat([cat_sal,num_sal],axis=1)
X,y=sal.drop('Salary',axis=1),sal['Salary']

In [ ]:
for a in alphas:
    model=Ridge(alpha=a)
    model.fit(X_train,y_train)
    y_pred=model.predict(X_test)
    scores.append([a,mean_absolute_error(y_test,y_pred)])
df_scores=pd.DataFrame(scores,columns=['alpha','score'])
df_scores.sort_values('score')

In [124]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

alphas=np.linspace(.001,15,30)
scores=[]
for a in alphas:
    model=Ridge(alpha=a)
    model.fit(X_train,y_train)
    y_pred=model.predict(X_test)
    scores.append([a,mean_absolute_error(y_test,y_pred)])
df_scores=pd.DataFrame(scores,columns=['alpha','score'])
df_scores.sort_values('Score')