Chronos (next Nos. Prediction) on Milk data set
-

https://huggingface.co/amazon/chronos-2

In [2]:
!pip install "chronos-forecasting>=2.0"

Requirement already satisfied: chronos-forecasting>=2.0 in c:\users\dbda.studentsdc\.conda\envs\hf\lib\site-packages (2.2.2)
Requirement already satisfied: accelerate<2,>=0.34 in c:\users\dbda.studentsdc\.conda\envs\hf\lib\site-packages (from chronos-forecasting>=2.0) (1.12.0)
Requirement already satisfied: einops<1,>=0.7.0 in c:\users\dbda.studentsdc\.conda\envs\hf\lib\site-packages (from chronos-forecasting>=2.0) (0.8.1)
Requirement already satisfied: numpy<3,>=1.21 in c:\users\dbda.studentsdc\.conda\envs\hf\lib\site-packages (from chronos-forecasting>=2.0) (2.4.0)
Requirement already satisfied: scikit-learn<2,>=1.6.0 in c:\users\dbda.studentsdc\.conda\envs\hf\lib\site-packages (from chronos-forecasting>=2.0) (1.8.0)
Requirement already satisfied: torch<3,>=2.2 in c:\users\dbda.studentsdc\.conda\envs\hf\lib\site-packages (from chronos-forecasting>=2.0) (2.9.1)
Requirement already satisfied: transformers<5,>=4.41 in c:\users\dbda.studentsdc\.conda\envs\hf\lib\site-packages (from chronos-forecasting>=2.0) (4.57.3)
Requirement already satisfied: packaging>=20.0 in c:\users\dbda.studentsdc\.conda\envs\hf\lib\site-packages (from accelerate<2,>=0.34->chronos-forecasting>=2.0) (25.0)
Requirement already satisfied: psutil in c:\users\dbda.studentsdc\.conda\envs\hf\lib\site-packages (from accelerate<2,>=0.34->chronos-forecasting>=2.0) (7.1.3)
Requirement already satisfied: pyyaml in c:\users\dbda.studentsdc\.conda\envs\hf\lib\site-packages (from accelerate<2,>=0.34->chronos-forecasting>=2.0) (6.0.3)
Requirement already satisfied: huggingface_hub>=0.21.0 in c:\users\dbda.studentsdc\.conda\envs\hf\lib\site-packages (from accelerate<2,>=0.34->chronos-forecasting>=2.0) (0.36.0)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\dbda.studentsdc\.conda\envs\hf\lib\site-packages (from accelerate<2,>=0.34->chronos-forecasting>=2.0) (0.7.0)
Requirement already satisfied: scipy>=1.10.0 in c:\users\dbda.studentsdc\.conda\envs\hf\lib\site-packages (from scikit-learn<2,>=1.6.0->chronos-forecasting>=2.0) (1.16.3)
Requirement already satisfied: joblib>=1.3.0 in c:\users\dbda.studentsdc\.conda\envs\hf\lib\site-packages (from scikit-learn<2,>=1.6.0->chronos-forecasting>=2.0) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\dbda.studentsdc\.conda\envs\hf\lib\site-packages (from scikit-learn<2,>=1.6.0->chronos-forecasting>=2.0) (3.6.0)
Requirement already satisfied: filelock in c:\users\dbda.studentsdc\.conda\envs\hf\lib\site-packages (from torch<3,>=2.2->chronos-forecasting>=2.0) (3.20.1)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\dbda.studentsdc\.conda\envs\hf\lib\site-packages (from torch<3,>=2.2->chronos-forecasting>=2.0) (4.15.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\dbda.studentsdc\.conda\envs\hf\lib\site-packages (from torch<3,>=2.2->chronos-forecasting>=2.0) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\dbda.studentsdc\.conda\envs\hf\lib\site-packages (from torch<3,>=2.2->chronos-forecasting>=2.0) (3.6.1)
Requirement already satisfied: jinja2 in c:\users\dbda.studentsdc\.conda\envs\hf\lib\site-packages (from torch<3,>=2.2->chronos-forecasting>=2.0) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in c:\users\dbda.studentsdc\.conda\envs\hf\lib\site-packages (from torch<3,>=2.2->chronos-forecasting>=2.0) (2025.12.0)
Requirement already satisfied: setuptools in c:\users\dbda.studentsdc\.conda\envs\hf\lib\site-packages (from torch<3,>=2.2->chronos-forecasting>=2.0) (80.9.0)
Requirement already satisfied: regex!=2019.12.17 in c:\users\dbda.studentsdc\.conda\envs\hf\lib\site-packages (from transformers<5,>=4.41->chronos-forecasting>=2.0) (2025.11.3)
Requirement already satisfied: requests in c:\users\dbda.studentsdc\.conda\envs\hf\lib\site-packages (from transformers<5,>=4.41->chronos-forecasting>=2.0) (2.32.5)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\dbda.studentsdc\.conda\envs\hf\lib\site-packages (from transformers<5,>=4.41->chronos-forecasting>=2.0) (0.22.1)
Requirement already satisfied: tqdm>=4.27 in c:\users\dbda.studentsdc\.conda\envs\hf\lib\site-packages (from transformers<5,>=4.41->chronos-forecasting>=2.0) (4.67.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\dbda.studentsdc\.conda\envs\hf\lib\site-packages (from sympy>=1.13.3->torch<3,>=2.2->chronos-forecasting>=2.0) (1.3.0)
Requirement already satisfied: colorama in c:\users\dbda.studentsdc\.conda\envs\hf\lib\site-packages (from tqdm>=4.27->transformers<5,>=4.41->chronos-forecasting>=2.0) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\dbda.studentsdc\.conda\envs\hf\lib\site-packages (from jinja2->torch<3,>=2.2->chronos-forecasting>=2.0) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\dbda.studentsdc\.conda\envs\hf\lib\site-packages (from requests->transformers<5,>=4.41->chronos-forecasting>=2.0) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\dbda.studentsdc\.conda\envs\hf\lib\site-packages (from requests->transformers<5,>=4.41->chronos-forecasting>=2.0) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\dbda.studentsdc\.conda\envs\hf\lib\site-packages (from requests->transformers<5,>=4.41->chronos-forecasting>=2.0) (2.6.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\dbda.studentsdc\.conda\envs\hf\lib\site-packages (from requests->transformers<5,>=4.41->chronos-forecasting>=2.0) (2025.11.12)

In [3]:
import pandas as pd
from chronos import Chronos2Pipeline
from sklearn.metrics import root_mean_squared_error
import os
os.chdir("C:/Users/dbda.STUDENTSDC/Desktop/Practical Machine Learning/Datasets")

c:\Users\dbda.STUDENTSDC\.conda\envs\hf\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [4]:
pipeline = Chronos2Pipeline.from_pretrained("amazon/chronos-2")

In [5]:
df =pd.read_csv("monthly-milk-production-pounds-p.csv")
df['timestamp'] = pd.date_range(start = '1962-01-01',periods=len(df),freq = 'ME') 
# df['timestamp'] name remain same for any dataset
df['id'] = 0  # id should be identical nos.
df.head()

     Month  Milk  timestamp  id
0  1962-01   589 1962-01-31   0
1  1962-02   561 1962-02-28   0
2  1962-03   640 1962-03-31   0
3  1962-04   656 1962-04-30   0
4  1962-05   727 1962-05-31   0

In [6]:
train = df.iloc[:-12]
test = df.iloc[-12:]
future_df = test.drop(columns=['Milk']).copy()
future_df['id'] = 0
future_df['timestamp'] = pd.date_range(start = '1962-01-01',periods=12,freq = 'ME')

In [7]:
pred_df = pipeline.predict_df(
    train,future_df = future_df,
    validate_inputs = False,
    prediction_length = 12, # nos. of steps to forecast
    id_column = 'id', # column indentifying diff. time series
    timestamp_column ='timestamp', # column  with date time info
    target='Milk'  # column(s) with time series values to predict
)
y_pred = pred_df['predictions']
pred_df

,id,timestamp,target_name,predictions,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9
0,0,1975-01-31,Milk,786.404114,750.643982,763.947998,773.192871,780.781250,786.404114,790.669250,793.034302,796.313538,803.100952
1,0,1975-02-28,Milk,774.365112,725.296265,744.533386,757.236389,766.772156,774.365112,780.884338,786.049561,793.008240,804.532471
2,0,1975-03-31,Milk,815.929504,736.506897,764.912231,786.125122,803.221375,815.929504,826.495117,835.486206,847.875854,864.236145
3,0,1975-04-30,Milk,822.120667,726.197571,759.273315,786.080627,806.424072,822.120667,838.070984,851.855225,867.199707,886.193909
4,0,1975-05-31,Milk,853.719666,728.153259,766.552002,802.217041,832.703613,853.719666,871.890747,889.098633,908.761536,927.736755
5,0,1975-06-30,Milk,843.946472,717.329102,761.573608,796.444458,824.229187,843.946472,865.507690,885.269531,908.301147,934.014771
6,0,1975-07-31,Milk,823.330139,709.555054,750.825073,778.559265,803.234253,823.330139,842.362366,861.070190,883.184631,909.616211
7,0,1975-08-31,Milk,798.273438,696.739624,733.075806,758.290771,780.531433,798.273438,814.940002,830.939819,849.447815,871.973450
8,0,1975-09-30,Milk,779.405518,696.931213,728.058228,748.261963,764.655457,779.405518,794.155029,807.440247,823.032227,844.815430
9,0,1975-10-31,Milk,779.678345,695.084778,725.327942,746.126160,763.625122,779.678345,794.635681,807.528320,822.273865,844.401917
10,0,1975-11-30,Milk,770.127808,687.695618,715.825500,736.422913,754.342346,770.127808,784.744385,796.901245,810.926453,831.881836
11,0,1975-12-31,Milk,777.531982,693.794617,721.697693,742.636169,760.901855,777.531982,792.743774,806.038635,820.784607,841.743713

In [ ]:
rmse_val = root_mean_squared_error(test['Milk'], y_pred)
print(f"RMSE: {rmse_val:.2f}")

RMSE: 66.73