In [12]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder,MinMaxScaler,LabelEncoder
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import (accuracy_score, classification_report, mean_absolute_error,mean_squared_error,
                             confusion_matrix, precision_score, recall_score, 
                             f1_score, roc_auc_score, roc_curve,log_loss)
import os
import sys
from sklearn.pipeline import Pipeline

# Bernoulli Naive Bayes

In [13]:
import warnings
warnings.filterwarnings('ignore')
os.chdir('D:\Machine Learning\Datasets')
cancer=pd.read_csv("d:\Machine Learning\Datasets\Cases\Cancer\Cancer.csv",index_col=1)
cancer

,subjid,menopause,tumor-size,inv-nodes,node-caps,deg-malig,breast,breast-quad,irradiat,Class
age,,,,,,,,,,
40-49,1,premeno,15 to 19,0 to 2,yes,three,right,left_up,no,recurrence-events
50-59,2,ge40,15 to 19,0 to 2,no,one,right,central,no,no-recurrence-events
50-59,3,ge40,35 to 39,0 to 2,no,two,left,left_low,no,recurrence-events
40-49,4,premeno,35 to 39,0 to 2,yes,three,right,left_low,yes,no-recurrence-events
40-49,5,premeno,30 to 34,3 to 5,yes,two,left,right_up,no,recurrence-events
...,...,...,...,...,...,...,...,...,...,...
50-59,282,ge40,30 to 34,6 to 8,yes,two,left,left_low,no,no-recurrence-events
50-59,283,premeno,25 to 29,3 to 5,yes,two,left,left_low,yes,no-recurrence-events
30-39,284,premeno,30 to 34,6 to 8,yes,two,right,right_up,no,no-recurrence-events
50-59,285,premeno,15 to 19,0 to 2,no,two,right,left_low,no,no-recurrence-events
50-59,286,ge40,40 to 44,0 to 2,no,three,left,right_up,no,no-recurrence-events

In [14]:



le=LabelEncoder()
cancer['Class']=le.fit_transform(cancer['Class'])

In [15]:
X,y=cancer.drop('Class',axis=1),cancer['Class']

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=25,stratify=y)
print(f"Training samples: {X_train.shape[0]}, Test samples: {X_test.shape[0]}")

Training samples: 200, Test samples: 86

In [23]:
ohe=OneHotEncoder(sparse_output=False, handle_unknown='ignore').set_output(transform='pandas')
X_train_ohe=ohe.fit_transform(X_train)
X_test_ohe=ohe.transform(X_test)

In [26]:
nb=BernoulliNB()
nb.fit(X_train_ohe,y_train)
y_pred_prob=nb.predict_proba(X_test_ohe)
print('log loss: ',log_loss(y_test,y_pred_prob))
y_pred=nb.predict(X_test_ohe)
print('Accuracy Score: ',accuracy_score(y_test,y_pred))

log loss:  0.8966170799322112
Accuracy Score:  0.7209302325581395

# Kernal navies bayes

In [27]:
from sklearn.naive_bayes import GaussianNB

In [32]:
import warnings
warnings.filterwarnings('ignore')
os.chdir('D:\Machine Learning\Datasets')
glass=pd.read_csv("D:\Machine Learning\Datasets\Cases\Glass_Identification\Glass.csv")
glass

,RI,Na,Mg,Al,Si,K,Ca,Ba,Fe,Type
0,1.52101,13.64,4.49,1.10,71.78,0.06,8.75,0.00,0.0,building_windows_float_processed
1,1.51761,13.89,3.60,1.36,72.73,0.48,7.83,0.00,0.0,building_windows_float_processed
2,1.51618,13.53,3.55,1.54,72.99,0.39,7.78,0.00,0.0,building_windows_float_processed
3,1.51766,13.21,3.69,1.29,72.61,0.57,8.22,0.00,0.0,building_windows_float_processed
4,1.51742,13.27,3.62,1.24,73.08,0.55,8.07,0.00,0.0,building_windows_float_processed
...,...,...,...,...,...,...,...,...,...,...
209,1.51623,14.14,0.00,2.88,72.61,0.08,9.18,1.06,0.0,headlamps
210,1.51685,14.92,0.00,1.99,73.06,0.00,8.40,1.59,0.0,headlamps
211,1.52065,14.36,0.00,2.02,73.42,0.00,8.44,1.64,0.0,headlamps
212,1.51651,14.38,0.00,1.94,73.61,0.00,8.48,1.57,0.0,headlamps
213,1.51711,14.23,0.00,2.08,73.36,0.00,8.62,1.67,0.0,headlamps

In [34]:

le=LabelEncoder()
glass['Type']=le.fit_transform(glass['Type'])

X,y=glass.drop('Type',axis=1),glass['Type']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=25,stratify=y)
print(f"Training samples: {X_train.shape[0]}, Test samples: {X_test.shape[0]}")

Training samples: 149, Test samples: 65

In [36]:
#to convert type cat to numeric
ohe=OneHotEncoder(sparse_output=False, handle_unknown='ignore').set_output(transform='pandas')
X_train_ohe=ohe.fit_transform(X_train)
X_test_ohe=ohe.transform(X_test)

In [38]:
nb=GaussianNB()
nb.fit(X_train_ohe,y_train)
y_pred_prob=nb.predict_proba(X_test_ohe)
print('log loss: ',log_loss(y_test,y_pred_prob))
y_pred=nb.predict(X_test_ohe)
print('Accuracy Score: ',accuracy_score(y_test,y_pred))

log loss:  17.7445678223346
Accuracy Score:  0.5076923076923077

# HR

In [39]:
hr=pd.read_csv("D:\Machine Learning\Datasets\HR_comma_sep.csv")
hr

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,Department,salary
0,0.38,0.53,2,157,3,0,1,0,sales,low
1,0.80,0.86,5,262,6,0,1,0,sales,medium
2,0.10,0.77,6,247,4,0,1,0,sales,low
3,0.92,0.85,5,259,5,0,1,0,sales,low
4,0.89,1.00,5,224,5,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...,...
14990,0.40,0.57,2,151,3,0,1,0,support,low
14991,0.37,0.48,2,160,3,0,1,0,support,low
14992,0.37,0.53,2,143,3,0,1,0,support,low
14993,0.11,0.96,6,280,4,0,1,0,support,low
14994,0.37,0.52,2,158,3,0,1,0,support,low

In [43]:
X,y=hr.drop('left',axis=1),hr['left']

In [44]:
from sklearn.compose import ColumnTransformer, make_column_selector
ohe=OneHotEncoder(drop='first',sparse_output=False).set_output(transform='pandas') # one hot encoder
col_trnf=ColumnTransformer([('OHE',ohe,make_column_selector(dtype_include=object))],remainder='passthrough',verbose_feature_names_out=True)
col_trnf=col_trnf.set_output(transform='pandas')
X=col_trnf.fit_transform(X)

In [45]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=25,stratify=y)
print(f"Training samples: {X_train.shape[0]}, Test samples: {X_test.shape[0]}")

Training samples: 10496, Test samples: 4499

In [48]:
nb=GaussianNB()
nb.fit(X_train,y_train)
y_pred_prob=nb.predict_proba(X_test)
print('log loss: ',log_loss(y_test,y_pred_prob))
y_pred=nb.predict(X_test)
print('Accuracy Score: ',accuracy_score(y_test,y_pred))

log loss:  0.7470421843093238
Accuracy Score:  0.7141587019337631

# LDA AS data transformer

In [55]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
import seaborn as sns

lda=LinearDiscriminantAnalysis().set_output(transform='pandas')

iris=pd.read_csv('iris.csv')
iris.columns

Index(['Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width',
       'Species'],
      dtype='object')

In [57]:
features=iris.drop('Species',axis=1)

In [59]:
from ipywidgets import widgets


def plot(col1,col2):
    sns.scatterplot(data=iris,x=col1,y=col2,hue='Species')
    plt.show()
widgets.interact(plot,col1=features,col2=features)

interactive(children=(Dropdown(description='col1', options=('Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Pe…

# Vehicle Dataset

In [65]:

lda=LinearDiscriminantAnalysis().set_output(transform='pandas')
vehicle=pd.read_csv("D:\Machine Learning\Datasets\Cases\Vehicle_Silhouettes\Vehicle.csv")
vehicle

,Comp,Circ,D.Circ,Rad.Ra,Pr.Axis.Ra,Max.L.Ra,Scat.Ra,Elong,Pr.Axis.Rect,Max.L.Rect,Sc.Var.Maxis,Sc.Var.maxis,Ra.Gyr,Skew.Maxis,Skew.maxis,Kurt.maxis,Kurt.Maxis,Holl.Ra,Class
0,95,48,83,178,72,10,162,42,20,159,176,379,184,70,6,16,187,197,van
1,91,41,84,141,57,9,149,45,19,143,170,330,158,72,9,14,189,199,van
2,104,50,106,209,66,10,207,32,23,158,223,635,220,73,14,9,188,196,saab
3,93,41,82,159,63,9,144,46,19,143,160,309,127,63,6,10,199,207,van
4,85,44,70,205,103,52,149,45,19,144,241,325,188,127,9,11,180,183,bus
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
841,93,39,87,183,64,8,169,40,20,134,200,422,149,72,7,25,188,195,saab
842,89,46,84,163,66,11,159,43,20,159,173,368,176,72,1,20,186,197,van
843,106,54,101,222,67,12,222,30,25,173,228,721,200,70,3,4,187,201,saab
844,86,36,78,146,58,7,135,50,18,124,155,270,148,66,0,25,190,195,saab
845,85,36,66,123,55,5,120,56,17,128,140,212,131,73,1,18,186,190,van

In [67]:
X,y=vehicle.drop('Class',axis=1),df['Class']
features=list(X.columns)

In [ ]:
def plot(col1,col2):
    sns.scatterplot(data=vehicle,x=col1,y=col2,hue='Class')
    plt.show()
widgets.interact(plot,col1=features,col2=features)

interactive(children=(Dropdown(description='col1', options=('Comp', 'Circ', 'D.Circ', 'Rad.Ra', 'Pr.Axis.Ra', …